name: PerkPlugin
version: '${project.version}'
main: perkplugin.perkplugin.PerkPlugin
api-version: '1.20'
commands:
  fly:
    description: Toggles Flying
    usage: /fly
    aliases: [f, flying, togglefly]
    permission-message: "NOT STINKY"
    permission: stinkers
  perks:
    description: Choose your perks
    usage: /perks
  lastInventory:
    description: Get Your Last Death Inventory
    usage: /lastInventory
  listPerks:
    description: List all Perks you have
    usage: /listPerks
